### ISSUE TITLE
appear some error after add needed two packages

### ISSUE THREAD

**Issue by 54dujianchao** [zoom/zoom-sdk-ios#18]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RPScreenRecorder", referenced from:
      objc-class-ref in MobileRTC
  "_OBJC_CLASS_$_CMMotionManager", referenced from:
      objc-class-ref in MobileRTC
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

could you help  me  What should I do

**Comment by Robusthxj** [comment]
ReplayKit.framework and CoreMotion.framework cannot support in Simulator, please set the status from Required to Optional, Please refer to what MobileRTCSample did.

**Comment by 54dujianchao** [comment]
I use the old zoom SDK could run on the simulator 。  However , when i update the lastest SDK , had appear The above problems arise。

**Comment by Robusthxj** [comment]
Please check "Link Binary with Libraries" in your project "Build Phases", you can refer to what MobileRTCSample did.

**Comment by 54dujianchao** [comment]
![image](https://user-images.githubusercontent.com/10827419/37330043-c0e5f32a-26da-11e8-91d2-6b22b51e1881.png)

maybe not the issue

**Comment by 54dujianchao** [comment]
Has been solved, but I feel a bit , we could improve the website information

**Comment by 54dujianchao** [comment]
Found a problem, after iOS users to join the webinar meeting, digital keyboard pops up, whether the SDK legacy bug

**Comment by noura-rizk** [comment]
Hi, did you find solution for this issue I tried the above solutions but still the same? I'm using xcode 9 swift 4.

**Comment by carsonzoom** [comment]
Hi! Thanks for using Zoom iOS SDK. This issue is being closed since it is not active for a while. If this is still an issue with the latest version of our SDK, please create a new issue and make sure the template is fully filled out. Thanks! :)
